sudo: required

language: ruby

branches:
  only:
  - master

services:
  - docker

install:
  - echo "install nothing!"

script:
  - docker --version
  - docker build -t ruby-postgresql-nodejs .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
