sudo: required

language: ruby

branches:
  only:
  - master

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker build -t ruby-postgresql-nodejs .
